### ISSUE TITLE
New usage scenario?

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/datapackage-ui#202]
There are currently [3 usage scenarios](https://github.com/okfn/datapackagist/blob/master/README.md#scenarios) proposed:
1. Starting from scratch
2. Edit an existing datapackage.json
3. Using DataPackagist via a link from CKAN or DKAN 
### Scenario 4

Create datapackage.json from CKAN dataset and resource links / identifiers
#### How would it work?
- The user would enter the dataset homepage url (or package name) into a form.
- Then an [API call](https://github.com/okfn/datapackagist/blob/master/README.md#api-via-query-params) would start creating the data package e.g. http://datapackagist.okfnlabs.org/base/from/?url=http%3A%2F%2Fdata.qld.gov.au%2Fapi%2Faction%2Fpackage_show%3Fid%3Ddays-lost-for-tmr-employee-injuries 
- then the csv data resources associated with the dataset would be determined 
- an automated process would perform the equivalent of Uploading the data file(s)
  ![upload](https://cloud.githubusercontent.com/assets/9379524/12162669/048ff092-b551-11e5-8c0f-f216702e889c.PNG)
#### Why is is needed?
- Many publishers are likely to have many datasets already published in CKAN.
- Not all publishers are able to make changes to the portal they publish on (voiding scenario 3)
- Many publishers will not have an existing datapackage.json file (voiding scenario 2)
- Publishers don't want to do multiple cut and pastes from their existing CKAN dataset metadata to use scenario 1.

**Comment by pwalsh** [comment]
@Stephen-Gates this is already implemented, but currently broken https://github.com/okfn/datapackagist/issues/201

The basic README is here (mostly aimed at developers): https://github.com/okfn/datapackagist#integrations

Essentially, portals could integrate with this directly, which is what we'll be doing for DKAN in Cambridgeshire, or, of you know the API, it can be done "programmatically".

Ideas to refine this feature are appreciated, and if you follow issue #201 you'll get notified when we fix the existing implementation, likely this Friday ( cc @borysyuk  )

**Comment by Stephen-Gates** [comment]
@pwalsh Great!

I guess not having access to programmers or the ability to change the portal, I was looking for a simple UI to enable non-technical publishers to generate packages easily by cutting and pasting a url.

As an alternate approach, we can manually construct the url (as I did above), then with #201 fixed, I should get a datapackage to further refine.

**Comment by pwalsh** [comment]
@Stephen-Gates A simple UI can be useful, but there are some difficulties. 

We need to know the URL of the API response for the object, and for a "non-programmer" to know that, they need to be able to get it from the "normal" HTML page for the dataset on CKAN or DKAN. 

However, these platforms do not give that, and further, it is not easy or reliable to try to detect the API response for the given dataset from that normal HTML page, the reasons being:

* Any D/CKAN install could ship custom templates that change the rendered content
* Human readable slugs seem to be able to change, at least on CKAN
* The normal templates do not use the unique identifiers on those pages, so that is not available to use in automatically detecting the correct API response

@amercader if you have any additions/comments on above please jump in :)

Considering above, what we can do that would consistently work, would be:

* Add an optional "from remote" UI, where:
  * The user pastes the **API URL**
  * The users says if it is CKAN or DKAN or whatever remotes we support
  * The user clicks populate and then the Data Package is created from the remote resource

So, this does require that the user knows the API URLs, but it would at least be a start in the direction you are indicating, and, as far as I see now, is the only way we can do this 100% reliably in a generic way. WDYT?

**Comment by Stephen-Gates** [comment]
Thanks @pwalsh - seems like a step in the right direction. Hopefully over time the process could be simplified.

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/datapackage-ui/issues/227
